name: lab11_13_deez_nuts
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_messaging: ^15.2.6
  firebase_remote_config: ^5.4.4
  google_sign_in: ^6.3.0
  sqflite: ^2.4.2
  uuid: ^4.5.1
  path: ^1.9.1
  path_provider: ^2.1.5
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^17.2.3
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
  build_test: ^2.2.1
  shared_preferences_platform_interface: any
  firebase_auth_platform_interface: any
  firebase_core_platform_interface: any

flutter:
  uses-material-design: true
  assets:
    - assets/
